export interface DrainagePipe {
  id: string;
  geocode: string;
  vulnerabilityRating: "high" | "moderate" | "low";
  location: string;
  installDate: string;
  lastInspection: string;
  diameter: number;
  material: string;
  condition: string;
}

export const drainagePipesData: DrainagePipe[] = [
  {
    id: "1",
    geocode: "GC-001-A4",
    vulnerabilityRating: "high",
    location: "Main Street & 1st Ave",
    installDate: "1985-03-15",
    lastInspection: "2024-01-15",
    diameter: 24,
    material: "Cast Iron",
    condition: "Severe corrosion detected",
  },
  {
    id: "2",
    geocode: "GC-002-B7",
    vulnerabilityRating: "moderate",
    location: "Oak Avenue & 3rd Street",
    installDate: "1992-07-22",
    lastInspection: "2024-02-10",
    diameter: 18,
    material: "PVC",
    condition: "Minor cracks observed",
  },
  {
    id: "3",
    geocode: "GC-003-C2",
    vulnerabilityRating: "low",
    location: "Pine Road & 5th Avenue",
    installDate: "2010-11-08",
    lastInspection: "2024-01-28",
    diameter: 30,
    material: "HDPE",
    condition: "Good condition",
  },
  {
    id: "4",
    geocode: "GC-004-D9",
    vulnerabilityRating: "high",
    location: "Elm Street & 2nd Avenue",
    installDate: "1978-09-12",
    lastInspection: "2024-01-20",
    diameter: 20,
    material: "Clay",
    condition: "Root intrusion and cracking",
  },
  {
    id: "5",
    geocode: "GC-005-E1",
    vulnerabilityRating: "low",
    location: "Maple Drive & 4th Street",
    installDate: "2015-05-30",
    lastInspection: "2024-02-05",
    diameter: 36,
    material: "Concrete",
    condition: "Excellent condition",
  },
  {
    id: "6",
    geocode: "GC-006-F8",
    vulnerabilityRating: "moderate",
    location: "Cedar Lane & 6th Avenue",
    installDate: "1995-12-18",
    lastInspection: "2024-01-12",
    diameter: 24,
    material: "Steel",
    condition: "Surface rust present",
  },
  {
    id: "7",
    geocode: "GC-007-G3",
    vulnerabilityRating: "high",
    location: "Birch Boulevard & 7th Street",
    installDate: "1982-04-25",
    lastInspection: "2024-02-01",
    diameter: 16,
    material: "Cast Iron",
    condition: "Significant deterioration",
  },
  {
    id: "8",
    geocode: "GC-008-H6",
    vulnerabilityRating: "low",
    location: "Willow Way & 8th Avenue",
    installDate: "2018-08-14",
    lastInspection: "2024-01-25",
    diameter: 42,
    material: "HDPE",
    condition: "Like new condition",
  },
  {
    id: "9",
    geocode: "GC-009-I5",
    vulnerabilityRating: "moderate",
    location: "Spruce Street & 9th Avenue",
    installDate: "1998-02-10",
    lastInspection: "2024-02-08",
    diameter: 28,
    material: "PVC",
    condition: "Minor wear and tear",
  },
  {
    id: "10",
    geocode: "GC-010-J4",
    vulnerabilityRating: "high",
    location: "Poplar Place & 10th Street",
    installDate: "1975-06-30",
    lastInspection: "2024-01-18",
    diameter: 22,
    material: "Clay",
    condition: "Multiple joint failures",
  },
  {
    id: "11",
    geocode: "GC-011-K7",
    vulnerabilityRating: "low",
    location: "Ash Avenue & 11th Street",
    installDate: "2020-03-22",
    lastInspection: "2024-02-12",
    diameter: 48,
    material: "Concrete",
    condition: "Perfect structural integrity",
  },
  {
    id: "12",
    geocode: "GC-012-L2",
    vulnerabilityRating: "moderate",
    location: "Hickory Hill & 12th Avenue",
    installDate: "1990-10-15",
    lastInspection: "2024-01-30",
    diameter: 32,
    material: "Steel",
    condition: "Moderate corrosion",
  },
];
